services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
